version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running tests"
      - pytest tests/

  build:
    commands:
      - echo "Launching SageMaker ETL/training"
      - python pipelines/pipeline.py
      - echo "Deploying SageMaker endpoint"
      - python pipelines/deploy_endpoint.py